### ISSUE TITLE
The issue with the flow generated using the GUI

### ISSUE THREAD

**Issue by Mr-Ma-yikun** [dangeng/motion_guidance#2]
Hello, I've been using your GUI program recently. I found the mask I obtained is normal, but the flow I obtained covers the entire screen rather than just the target area. Is there something wrong with the program?
![X GOG~Q4`M3VAZ$Q@X(GISQ](https://github.com/dangeng/motion_guidance/assets/72637909/0d8ee4cc-35f6-4599-baf2-df6370ebbd8b)

**Comment by dangeng** [comment]
Hey, the GUI saves the flow and the mask separately in case you want to make some tweaks to the mask. If you want the flow to be masked as well you could multiply the flow by the mask after running the GUI.
