### ISSUE TITLE
General Queries

### ISSUE THREAD

**Issue by tgy1221** [dangeng/motion_guidance#3]
Hi, thanks for the great work! I have a couple of questions: 

1. From Section 4.5, is the curated dataset and the KITTI dataset that you generated automatically is available? Furthemore, is the code for the evaluation available, which includes the calculation of the CLIP Visual Similarity and Flow Loss, and the modified InstructPix2Pix, Forward Warp with SDEdit, RePaint,  DragGAN. 
2. Is the code for the Motion Transfer (Section 4.6) available, it would be helpful if it's released. 
3. From the GUI code, it seems like it only contains translation, rotation, and scaling. May I know where I can find the implementation of thestretching and interpolated stretching.
![image](https://github.com/dangeng/motion_guidance/assets/68222791/8dd78fd7-f862-4f25-a840-c4d9ee80bc46)

Looking forward to hearing from you. 

Thanks a lot.

**Comment by dangeng** [comment]
Hi, I'm very sorry for the delay! I have all of this code (and data), but it's incredibly messy so I'd rather not push it to github. Can you email me and then I can send you the code that way? Thanks!
